params:

  seed: ${...seed}

  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
    mlp:
      units: [512, 256]
      activation: relu
      initializer:
        name: default
    log_std_bounds: [-5, 2]

  # 不加载已有模型（可改 True）
  load_checkpoint: False
  load_path: nn/DrivingTrajectoryTask.pth

  config:
    name: ${resolve_default:DrivingTrajectoryTaskSAC,${....experiment}}
    env_name: rlgpu
    multi_gpu: ${....multi_gpu}
    
    # 归一化 obs （轨迹任务通常需要）
    normalize_input: True

    # 奖励缩放
    reward_shaper:
      scale_value: 1.0

    # =============== 训练时间与 buffer  ===============
    max_epochs: 4000
    num_steps_per_episode: 1     # 一条轨迹=一个 episode
    save_best_after: 100
    save_frequency: 500

    gamma: 0.99
    init_alpha: 1.0
    alpha_lr: 0.001
    actor_lr: 0.0003
    critic_lr: 0.0003
    critic_tau: 0.005

    batch_size: 2048
    replay_buffer_size: 200000

    learnable_temperature: true

    # warmup
    num_seed_steps: 10
    num_warmup_steps: 10

    # 与 driver task 并行环境数量一致
    num_actors: ${....task.env.numEnvs}
